apiVersion: apps/v1
kind: Deployment
metadata:
  name: mi-app-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mi-app
  template:
    metadata:
      labels:
        app: mi-app
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        ports:
        - containerPort: 80
        # ESTE COMANDO ROTO HARÁ QUE EL POD FALLE INMEDIATAMENTE
        command: ["nginx", "-g", "daemon off;", "--config-invalid-flag"]