apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

labels:
- pairs:
    env: laboratorio
images:
- name: nginx
  newName: nginx
  newTag: 3b68a1fac1c94348ca6897adfaa07b07a00c4ee2
