name: GitOps CI-CD Pipeline

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'apps/mi-app/**'

jobs:
  update-manifest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar Kustomize en el Runner
        uses: imranismail/setup-kustomize@v2

      - name: Actualizar la etiqueta de la imagen con Kustomize
        run: |
          cd apps/mi-app
          kustomize edit set image nginx=nginx:1.26-alpine

      - name: Hacer Commit y Push de los cambios a Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add apps/mi-app/kustomization.yaml
          git commit -m "chore(ci): update nginx image to official 1.26-alpine" || exit 0
          git push